version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"      
    ports:
      - "8000:8000"
    command: uvicorn swh.graphql.app:app --host 0.0.0.0 --port 8000 --reload
