Initial Entry points
--------------------

origin(url) {
  url
  vsits(first:n) {
    totalCount
    edges {
      node {
        timestamp
      }
      cursor
    }
  }
}

visit {
  status
  timestamp
  snapshot
}

snapshots(origin-url, limit)  // not a must have

snapshot(sha1) {
  sha1
  origin
  branches(limit) {
     name
     head revision
  }
}

revision(sha1) {
  sha1
  author
  ...
  parent revisions(limit)
  directory
}

directory(sha1) {
  sha1
  name
  ...
  contents(limit)
  directories(limit)
}

content(sha1) {
  sha1
  name
  ...
}
